#!/bin/sh
PGBASE="/usr/local/pgsql"
PGDATA1="${PGBASE}/data1"
PGDATA2="${PGBASE}/data2"
PGDATA3="${PGBASE}/data3"
PGRP="${PGBASE}/pgrp"
PGLB="${PGBASE}/pglb"

# start cluster DBs
${PGBASE}/bin/pg_ctl -D ${PGDATA1} start
${PGBASE}/bin/pg_ctl -D ${PGDATA2} start
${PGBASE}/bin/pg_ctl -D ${PGDATA3} start

sleep 10 

#start load balancer
cd ${PGLB}
${PGBASE}/bin/pglb -D ${PGLB}

#start replication server
cd ${PGRP}
${PGBASE}/bin/pgreplicate -vn -D ${PGRP} > ${PGRP}/debug 2>&1

